sudo: false
language: node_js
node_js:
  - "node"
  - "6"
# The script actions are to check the project is valid.
# If using Travis for the project PLEASE MODIFY/REMOVE AS NEEDED.
script:
  - yarn run lint
  - yarn run coverage
  - yarn run build:dev
  - yarn run build:prod
