sudo: false
language: node_js
node_js:
  - "node"
# The script actions are to check the project is valid.
# If using Travis for the project PLEASE MODIFY/REMOVE AS NEEDED.
script:
  - npm run lint
  - npm run build:dev
  - npm run build:prod
  - npm run package
