sudo: false
language: node_js
node_js:
  - "node"
# The script actions are to check the project is valid.
# If using Travis for the project PLEASE MODIFY/REMOVE AS NEEDED.
script:
  - yarn lint
  - yarn package
